# SITE CONFIGURATION
#baseurl: ""
#url: "https://blog.gdgcloudhanoi.com"

# THEME-SPECIFIC CONFIGURATION
title: GDG Cloud Hanoi Tech Blog                                    # site's title
description: "GDG Cloud Hanoi Tech Blog"      # used by search engines
avatar: assets/img/gdg.png                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
# header_text: "GDG Cloud Hanoi"                                           # Change Blog header text
header_feature_image: assets/img/pexels/gdgcloudhanoi.png
footer_text: Powered by <a href="https://gdgcloudhanoi.com/">GDG Cloud Hanoi</a>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
katex: true                                             # Enable if using math markup
google_analytics: UA-126117321-2                                        # Tracking ID, e.g. "UA-000000-01"
disqus_shortname: blog-gdgcloudhanoi                                      # Your discus shortname for comments
layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons: ["facebook", "twitter", "linkedin"]                                          # In _data/social.yml
share_buttons: facebook                                          # In _data/social.yml
authors: truongnh                                                # In _data/authors.yml
language:                                               # In _data/language.yml

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", "vendor/*",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
